### ISSUE TITLE
W1 Público: Registrarse como usuario

### ISSUE THREAD

**Issue by jesQM** [jesQM/sdi1920-entrega2-302-315#1]
Los usuarios deben poder registrarse en la aplicación aportando un email, nombre, apellidos y una
contraseña (que deberá repetirse dos veces y coincidir entre sí).
El email del usuario no podrá estar repetido en el sistema, se debe informar al usuario de los errores en el
proceso de registro.
Pruebas Funcionales
[Prueba1] Registro de Usuario con datos válidos.
[Prueba2] Registro de Usuario con datos inválidos (email vacío, nombre vacío, apellidos vacíos).
[Prueba3] Registro de Usuario con datos inválidos (repetición de contraseña inválida).
[Prueba4] Registro de Usuario con datos inválidos (email existente).

**Comment by PabloCanalSuarez** [comment]
Faltan tests.
