### ISSUE TITLE
W10 Seguridad

### ISSUE THREAD

**Issue by jesQM** [jesQM/sdi1920-entrega2-302-315#10]
Deberá diseñarse adecuadamente la política de seguridad con los mecanismos de seguridad de Node.Js
para que no existan situaciones de vulnerabilidad en el acceso a recursos/acciones de usuarios registrados.
Pruebas Funcionales
[Prueba20] Intentar acceder sin estar autenticado a la opción de listado de usuarios. Se deberá volver al
formulario de login.
[Prueba21] Intentar acceder sin estar autenticado a la opción de listado de invitaciones de amistad recibida
de un usuario estándar. Se deberá volver al formulario de login.
[Prueba22] Intentar acceder estando autenticado como usuario standard a la lista de amigos de otro
usuario. Se deberá mostrar un mensaje de acción indebida.

**Comment by PabloCanalSuarez** [comment]
Faltan tests.
