### ISSUE TITLE
C4. Crear mensaje

### ISSUE THREAD

**Issue by jesQM** [jesQM/sdi1920-entrega2-302-315#19]
Desde la vista de chat el usuario debe poder crear un nuevo mensaje para ese amigo. Siendo el usuario el
emisor y el amigo el destino.
Pruebas Funcionales
[Prueba28] Acceder a la lista de mensajes de un amigo “chat” y crear un nuevo mensaje, validar que el
mensaje aparece en la lista de mensajes.

**Comment by PabloCanalSuarez** [comment]
Faltan tests.
