### ISSUE TITLE
C6 Mostrar el número de mensajes sin leer

### ISSUE THREAD

**Issue by jesQM** [jesQM/sdi1920-entrega2-302-315#21]
Se debe mostrar junto al nombre de cada amigo (en la lista de amigos) cuantos mensajes sin leer hay en
esa conversación.
El número de mensajes sin leer debe actualizarse en tiempo real, sin necesidad de recargar la página ni de
pulsar ningún botón. Es decir, debe haber un proceso automático que compruebe cada segundo si hay
nuevos mensajes.
Pruebas Funcionales
[Prueba30] Identificarse en la aplicación y enviar tres mensajes a un amigo, validar que los mensajes
enviados aparecen en el chat. Identificarse después con el usuario que recibido el mensaje y validar que el
número de mensajes sin leer aparece en la propia lista de amigos.

**Comment by PabloCanalSuarez** [comment]
Faltan tests y refrescar cada segundo.
