### ISSUE TITLE
W4 Usuario registrado: Listar todos los usuarios de la aplicación

### ISSUE THREAD

**Issue by jesQM** [jesQM/sdi1920-entrega2-302-315#4]
Se visualizará en una lista todos los usuarios de la aplicación. Para cada usuario se mostrará su nombre,
apellidos y email.
La lista debe incluir un sistema de paginación y mostrar 5 usuarios por página.
Debe incluirse una opción de menú principal, visible solo para usuarios en sesión que permita acceder al
listado de todos los usuarios de la aplicación.
Pruebas Funcionales
[Prueba11] Mostrar el listado de usuarios y comprobar que se muestran todos los que existen en el sistema.

**Comment by PabloCanalSuarez** [comment]
Faltan pruebas.
