### ISSUE TITLE
W9 Usuario registrado: Listar los usuarios amigos

### ISSUE THREAD

**Issue by jesQM** [jesQM/sdi1920-entrega2-302-315#9]
Se visualizará en una lista todos los usuarios amigos del usuario en sesión. Para cada usuario se mostrará
su nombre, apellidos y email.
La lista de amigos debe incluir un sistema de paginación y mostrar 5 usuarios por página.
Debe incluirse una opción de menú principal, visible solo para usuarios en sesión que permita acceder al
listado de todos los amigos del usuario en sesión.
[Prueba19] Mostrar el listado de amigos de un usuario. Comprobar que el listado contiene los amigos que
deben ser.

**Comment by PabloCanalSuarez** [comment]
Faltan tests.
